<?php
// $Id$

/**
 * @file Rules Web Hooks - Module file.
 */

/**
 * Implements of hook_entity_info().
 */
function rules_web_hook_entity_info() {
  return array(
    'rules_web_hook' => array(
      'label' => t('Web hook'),
      'controller class' => 'EntityAPIController',
      'base table' => 'rules_web_hook',
      'fieldable' => TRUE,
      'object keys' => array(
        'id' => 'id',
        'name' => 'name',
        'bundle' => 'name',
      ),
      'bundles' => array(),
      'exportable' => TRUE,
      'access callback' => 'rules_web_hook_access_callback',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function rules_web_hook_permission() {
  return array(
    'administer web hooks' =>  array(
      'title' => t('Administer web hooks'),
      'description' => t('Define web hooks and administer remote sites.'),
    ),
    'use web hooks' =>  array(
      'title' => t('Make use of web hooks'),
    ),
  );
}

/**
 * An access callback for the rules web entities.
 *
 * @see rules_web_entity_info()
 */
function rules_web_hook_access_callback($op, $entity_type, $entity = NULL, $account = NULL) {
  if ($op == 'view') {
    return user_access('use web hooks', $account);
  }
  return user_access('administer web hooks', $account);
}

/**
 * Implements hook_default_services_endpoint().
 */
function rules_web_hook_default_services_endpoint() {
  $endpoint = new stdClass;
  $endpoint->disabled = FALSE;
  $endpoint->endpoint = 'rules_web_hook';
  $endpoint->title = 'Rules Web Hooks Endpoint';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'rules_web';
  $endpoint->authentication = '';
  $endpoint->authentication_settings = FALSE;
  $endpoint->resources = array(
    'node' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 0,
        ),
      ),
    ),
    'comment' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 0,
        ),
      ),
    ),
    'user' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 0,
        ),
      ),
    ),
    'taxonomy_term' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 0,
        ),
      ),
    ),
    'taxonomy_vocabulary' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 0,
        ),
      ),
    ),
    'rules_web_hook' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 0,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 1,
        ),
      ),
    ),
    'entity_metadata' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 0,
        ),
        'retrieve' => array(
          'enabled' => 0,
        ),
        'update' => array(
          'enabled' => 0,
        ),
        'delete' => array(
          'enabled' => 0,
        ),
        'index' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  return array('test' => $endpoint);
}
